### ISSUE TITLE
Invalid Syntax in Python 2.6.6

### ISSUE THREAD

**Issue by zdravi** [joakimkarlsson/nose-terse-output#1]
```
Python 2.6.6 (r266:84292, Aug 12 2014, 07:57:07)
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import terseout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/terseout.py", line 41
    file_, line, *_ = self._first_local_stackframe(tb)
                 ^
SyntaxError: invalid syntax
>>>
```

It appears to be specifically related to the lack of *-syntax list expansion in Python 2.

**Comment by joakimkarlsson** [comment]
I managed to run 
https://github.com/joakimkarlsson/nose-terse-output/commit/963f725b4aed4921223265c3914e97f74e7874a8 on Python 2.7.8. Could you take a look and see how this works in 2.6.6, @zdravi ?

**Comment by zdravi** [comment]
Works fine on 2.6.6 for me. Thanks!
